In [1]:
import numpy as np

In [2]:
print(np)
print(np.__version__)

<module 'numpy' from 'C:\\Users\\box62\\.conda\\envs\\tf_base\\lib\\site-packages\\numpy\\__init__.py'>
1.20.0


range()
np.arange()
np.linspace()
不同

In [3]:
range(6)

range(0, 6)

In [4]:
for i in range(6):
    print(i)

0
1
2
3
4
5


In [5]:
range(1,6,3)

range(1, 6, 3)

In [7]:
for i in range(1,6,1):print(i)

1
2
3
4
5


____________arange___________________________

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(10.0)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [10]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [12]:
np.arange(1,10,2.0)

array([1., 3., 5., 7., 9.])

____________linspace________________________

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

- 指定在start到stop均分數值

- start:不可省

- stop:有時包含有時不包含，根據endpoint來選擇，默認包含

- num:指定均分的數量，默認為50

- endpoint:布爾值，可選，默認為True。包含stop就True,不包含就False

- retstep : 布爾值，可選，默認為False。如果為True,返回值和步長

In [14]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [16]:
np.linspace(1,10,endpoint=False) #默認生成50個，不包含stop:10

array([1.  , 1.18, 1.36, 1.54, 1.72, 1.9 , 2.08, 2.26, 2.44, 2.62, 2.8 ,
       2.98, 3.16, 3.34, 3.52, 3.7 , 3.88, 4.06, 4.24, 4.42, 4.6 , 4.78,
       4.96, 5.14, 5.32, 5.5 , 5.68, 5.86, 6.04, 6.22, 6.4 , 6.58, 6.76,
       6.94, 7.12, 7.3 , 7.48, 7.66, 7.84, 8.02, 8.2 , 8.38, 8.56, 8.74,
       8.92, 9.1 , 9.28, 9.46, 9.64, 9.82])

In [17]:
 np.linspace(2.0, 3.0, num=5)  #指定生成5個，包含stop:10

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [18]:
np.linspace(2,3,num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [19]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [20]:
 np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

_____________ NdArray_____________



In [23]:
a = np.arange(15).reshape(3, 5)

In [24]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


- ndarray.ndim

- ndarray.shape

- ndarray.size

- ndarray.dtype

- ndarray.itemsize

- ndarray.data

In [26]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
#print(a.itsize)
print(a.data)

2
(3, 5)
15
int32


list(a) 只會把第一層的元素轉換成 List，多層的話只有第一層會轉；

tolist() 才能達成多層的型態轉換

In [28]:
b = list(a)

In [33]:
a.tolist()

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [ ]:
|

我們整理出四個 Numpy 更強大的特性：



- Numpy 使用更少的空間儲存資料

- Numpy 對於元素的查找更加快速高效

- Numpy 可以更好地表示數學中的向量/矩陣

- Numpy 支援了矩陣相關的數學運算
