In [1]:
import numpy as np

# 1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。

In [12]:
a = np.arange(0,21,1)

In [22]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

# 2.呈上題，將以上數列取出偶數。

In [27]:
filter_a = a% 2 == 0

 b = a[filter_a]

In [30]:
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [93]:
b_2 = a[(a%2 ==0) & (a !=0)]

In [95]:
b_2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

# 3.呈1題，將數列取出3的倍數。

In [42]:
filter_a_2 = (a% 3 == 0 )

In [43]:
c = a[filter_a_2]

In [45]:
filter_c = ( c!=0 )

In [46]:
c = c[filter_c]

In [47]:
c

array([ 3,  6,  9, 12, 15, 18])

In [96]:
c_2 = a[(a%3 ==0) & (a !=0)]
c_2

array([ 3,  6,  9, 12, 15, 18])

# 4.請問下列兩種將 Array 轉換成 List 的方式有何不同？

In [49]:
print('list(a): ', list(a))
print('tolist(): ', a.tolist())

list(a):  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
tolist():  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


不知道...

# 5.請試著在程式中印出以下三個 NdArray 的屬性？

（屬性：ndim、shape、size、dtype、itemsize、length、type）

In [50]:
print(a.size)

21


In [51]:
print(a.shape)

(21,)


In [52]:
print(a.dtype)

int32


In [53]:
print(a.itemsize)

4


In [57]:
print(a.ndim) # number of dimensions

1


# 6.如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。

In [58]:
list_a = list(a)

In [59]:
list_a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [63]:
type(list_a)

list

In [64]:
list_a2= a.tolist()

In [65]:
type(list_a2)

list