# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

In [3]:
import numpy as np

# 作業 

### 1. 題目 :
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']

sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']

weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]

rank_list = [8,1,5,4,7,6,2,3]

myopia_list = [True,True,False,False,True,True,False,False]

(1) 將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]

(2)呈上題，將array中體重(weight)數據集取出算出全部平均體重

(3)呈上題，進一步算出男生(sex欄位是boy)平均體重、女生(sex欄位是girl)平均體重

In [4]:
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]

In [10]:
dt = np.dtype({'names':('name','sex','weight','rank','myopia'),'formats':((np.str_, 5),(np.str_, 5),np.float16,np.uint8,'U5')})

In [11]:
c = np.zeros(8,dtype=dt)

In [12]:
c['name']   = name_list
c['sex']    = sex_list
c['weight'] = weight_list
c['rank']   = rank_list
c['myopia'] = myopia_list



(1)答案

In [15]:
c

array([('小明', 'boy', 67.5, 8, 'True'), ('小華', 'boy', 75.3, 1, 'True'),
       ('小菁', 'girl', 50.1, 5, 'False'), ('小美', 'girl', 45.5, 4, 'False'),
       ('小張', 'boy', 80.8, 7, 'True'), ('John', 'boy', 90.4, 6, 'True'),
       ('Mark', 'boy', 78.4, 2, 'False'),
       ('Tom', 'boy', 70.7, 3, 'False')],
      dtype=[('name', '<U5'), ('sex', '<U5'), ('weight', '<f2'), ('rank', 'u1'), ('myopia', '<U5')])

(2)答案

In [43]:
c['weight'].mean() #all weight mean

69.8

(3)答案

In [42]:
c[c['sex'] == 'boy']['weight'].mean() #boy's weight mean

77.2

In [41]:
c[c['sex'] == 'girl']['weight'].mean() #girl's weight mean

47.8

### 2. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [45]:
print(np.zeros((2, 3)))
print(np.empty((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


array([[9.87682824e-312, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 1.04082753e-047],
       [5.20748927e-090, 9.96444600e-047, 9.99131758e-048,
        2.12609514e+160, 3.99910963e+252, 5.82471487e+257]])

### 答案:

np.zeros  建立元素為0的大小矩陣

np.empty  建立不需要給定起始值 執行速度快 用於初始化使定大小的陣列 對初始資料不要求

### 3. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [66]:
a = np.random.rand(2, 3)*3

In [67]:
a

array([[1.10389103, 1.53630945, 2.97075648],
       [1.13968974, 1.81398565, 2.34229437]])

In [68]:
a = np.array(a,dtype=int)

In [69]:
a

array([[1, 1, 2],
       [1, 1, 2]])

### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [70]:
m = 20
n = 40


In [71]:
a = 20 + (40-20) * np.random.rand(2, 3)
a

array([[24.71129691, 37.33796794, 23.24572679],
       [38.87321854, 35.51599092, 28.85095502]])