In [1]:
# 載入 NumPy 套件
import numpy as np

In [52]:
a = np.array( [20,30,40,50] )


In [57]:
a

array([20, 30, 40, 50])

In [55]:
a_t = a.reshape(4,1)

In [56]:
a_t

array([[20],
       [30],
       [40],
       [50]])

In [58]:
a + a_t

array([[ 40,  50,  60,  70],
       [ 50,  60,  70,  80],
       [ 60,  70,  80,  90],
       [ 70,  80,  90, 100]])

In [61]:
a * a_t

array([[ 400,  600,  800, 1000],
       [ 600,  900, 1200, 1500],
       [ 800, 1200, 1600, 2000],
       [1000, 1500, 2000, 2500]])

In [62]:
np.power(a_t,2)

array([[ 400],
       [ 900],
       [1600],
       [2500]], dtype=int32)

In [63]:
np.sqrt(a_t)

array([[4.47213595],
       [5.47722558],
       [6.32455532],
       [7.07106781]])

In [64]:
np.e

2.718281828459045

In [65]:
np.exp(1)

2.718281828459045

In [67]:
np.exp(np.arange(5))

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [76]:
np.log2(16)

4.0

In [79]:
np.log2([16,8,5])

array([4.        , 3.        , 2.32192809])

In [77]:
np.log2([-1,1,2])

<ipython-input-77-81a4b9e56b61>:1: RuntimeWarning: invalid value encountered in log2
  np.log2([-1,1,2])


array([nan,  0.,  1.])