In [2]:
import numpy as np

# 作業一

english_score = np.array([55,89,76,65,48,70])

math_score = np.array([60,85,60,68,55,60])

chinese_score = np.array([65,90,82,72,66,77])

上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，運用上列數據回答下列問題。



有多少學生英文成績比數學成績高?
是否全班同學最高分都是國文?

In [46]:
english_score = np.array([55,89,76,65,48,70])

math_score = np.array([60,85,60,68,55,60])

chinese_score = np.array([65,90,82,72,66,77])

In [47]:
dt = np.dtype({'names':('english','math','chinese'),'formats':(np.uint8,np.uint8,np.uint8)})

In [48]:
c = np.zeros(6,dtype=dt)

In [49]:
c['english'] =english_score
c['math'] =math_score
c['chinese'] =chinese_score

1.答案

In [50]:
c[c['english'] > c['math']].size #答案

3

2.答案

In [57]:
(np.max(c['chinese']) >  np.max(c['math'])) and (np.max(c['chinese']) >  np.max(c['english'])) 

True

# 作業二

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [71]:
a = np.arange(0,11,1)

a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
a[(a >=3) & (a <= 6)] = -a[(a >=3) & (a <= 6)]

In [73]:
a

array([ 0,  1,  2, -3, -4, -5, -6,  7,  8,  9, 10])

### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [74]:
A = np.random.rand(3, 6)



In [76]:
A[A >0.5]

array([0.79787283, 0.57306004, 0.86495219, 0.6035789 , 0.83692794,
       0.82339108, 0.95694314, 0.88674104, 0.59945994, 0.51304713,
       0.92401809, 0.87332829])