作業目標<br>
活用矩陣運算，實做線性代數<br>
作業重點<br>
線性代數公式應用<br>
矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

題目:<br>
array1 = np.array([[10, 8], [3, 5]]) <br>
1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
2. 運用上列array計算特徵值、特徵向量?
3. 運用上列array計算SVD?

In [1]:
import numpy as np

In [9]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])

invarray1=np.linalg.inv(array1)
print(array1@invarray1)

[[1. 0.]
 [0. 1.]]


In [10]:
array1

array([[10,  8],
       [ 3,  5]])

In [11]:
invarray1

array([[ 0.19230769, -0.30769231],
       [-0.11538462,  0.38461538]])

[[164  70]
 [ 70  34]]


In [12]:
#2. 運用上列array計算特徵值、特徵向量?
w, v = np.linalg.eig(array1)

print(w)
print(v)

[13.  2.]
[[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [ ]:
#3. 運用上列array計算SVD?

In [14]:
u, s, vh = np.linalg.svd(array1)

pri

NameError: name 'pri' is not defined