In [2]:
import numpy as np

# 作業 

### 1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```


In [5]:
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] )

In [7]:
print(a + a)
print(a + b)
print(a + c)
print(a + d)
#print(a + e) #不符合廣播規則

[ 40  60  80 100]
[21 32 43 54]
[21 31 41 51]
[21 31 41 51]


### 2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？


In [9]:
A = np.ones(3)*1
B = np.ones(3)*2


print(A)
print(B)


[1. 1. 1.]
[2. 2. 2.]


In [10]:
# 不用迴圈
print((A + B)*(-A/2))


[-1.5 -1.5 -1.5]


In [14]:
result=[]
for i in np.arange(A.size):
    result.append((A[i] + B[i])*(-A[i]/2))

In [15]:
result

[-1.5, -1.5, -1.5]

### 3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？


In [17]:
A = np.ones((1,6))
B = np.ones((6,1))


In [19]:
A

array([[1., 1., 1., 1., 1., 1.]])

In [20]:
B

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [27]:
C= np.dot(A,B)

In [28]:
C

array([[6.]])

In [29]:
D= np.outer(A, B)

In [30]:
D

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [31]:
A@B

array([[6.]])